baseurl         = "/"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 2
#SectionPagesMenu = "main"
canonifyurls    = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "Henao-Tamayo Lab"
  subtitle    = "Mycobacterial Research Laboratories | Colorado State University| Fort Collins, CO"
  copyright   = "© 2018"

  cover       = "img/banner.png"
  description = ""
  metaDescription = ""
  googleAnalytics = "UA-148659710-1"
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "bkarger"
  linkedinName = ""
  mediumName = ""

  logo = ""
  orgName = "CSU"
  orgWebsite = "https://www.colostate.edu/"
  orgDescription = "University Website"

  showSupport = false

  author = "BK"
  authorAvatar = "img/CSU-Logo.png"
  authorLocation = "Fort Collins, CO"
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Colorado State University Website"
  url = "https://www.colostate.edu/"
  weight = 95
